### ISSUE TITLE
Rich text edition in open questions flickrs

### ISSUE THREAD

**Issue by xgo-work** [Heigvd/Wegas#1890]
Open questions with a rich text editor gets rendered crazily. Bug happens only on specific space sizes (small widths are stable large ones trigger the problem). Moreover, hard-coding the width of the div containing the component hides the problem, which seems to indicate some CSS related issue.

To reproduce, 
- open UnPeuDeReact, select the questions tab. 
- Select some open question, for example "nouvelle question ouverte" at the bottom
- make sure the page display has a big width

Symptoms : flickering pointer, impossible to edit the fields, the rich text editor does not initialize properly

**Comment by audreyhuguenin** [comment]
- The problem seems to be in the rendering of Jodit Text Editor. If display: none the problem solves but not when visisbility: hidden. -> meaning if it renders but is not shown, the problems still is alive. 
- -Setting a height for the ChoiceCntainer comp seems to avoir flickering jodit display, unless user resizes window.
- Moreover, this flickering seems to make ChoiceContainer re-renders 10 times a second if no height set.
